### ISSUE TITLE
Bug: result sharing card floating point error

### ISSUE THREAD

**Issue by xmliszt** [xmliszt/taboo-ai#245]
![image](https://github.com/xmliszt/taboo-ai/assets/44829092/c7669821-c524-4096-ae6e-bc196cc14a3b)

**Comment by V-Mokhun** [comment]
Hey, I think I found the cause of this problem:
There is a totalScore variable in results-share-alert-dialog.tsx and it should probably be rounded when displaying it to the user. If you'd like, you can assign me to this issue and I'll fix it.

![telegram-cloud-photo-size-2-5454366938890359785-y](https://github.com/xmliszt/taboo-ai/assets/78966165/ca764ab4-12e4-491c-96a8-0964546555b9)

**Comment by xmliszt** [comment]
> Hey, I think I found the cause of this problem: There is a totalScore variable in results-share-alert-dialog.tsx and it should probably be rounded when displaying it to the user. If you'd like, you can assign me to this issue and I'll fix it.
> 
> ![telegram-cloud-photo-size-2-5454366938890359785-y](https://private-user-images.githubusercontent.com/78966165/289383995-ca764ab4-12e4-491c-96a8-0964546555b9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTc5MjcsIm5iZiI6MTcwMjI1NzYyNywicGF0aCI6Ii83ODk2NjE2NS8yODkzODM5OTUtY2E3NjRhYjQtMTJlNC00OTFjLTk2YTgtMDk2NDU0NjU1NWI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAxMjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODIyY2M1MWRiZjAwY2FlNzYwMGQwZTNhNGU0NjFjNjFkOWMxZWU4MzJhMDAwNGYwZDFhMGFlODM5N2Q2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_COisiACrX7WeaTiLLPcbKD6qviUuDUha8AeEfK07M)

Hey @V-Mokhun ! Thanks for spotting the problem and the help! Sure I will assign the issue to you and you can try directly PR to `main` instead as a quick fix. (I'm currently working on a major feature that merges into `preview` branch, but no worries, I will update the GitHub actions pipeline to run a preview build when you PR targeting `main`) Cheers!

**Comment by V-Mokhun** [comment]
Hey, I think I finished it, would appreciate it if you take a look. Is there anything else I may help with?

**Comment by xmliszt** [comment]
> Hey, I think I finished it, would appreciate it if you take a look. Is there anything else I may help with?

Thanks a lot! Looks good :)
