### ISSUE TITLE
Bug: Able to scroll down past the end of page in specific pages

### ISSUE THREAD

**Issue by austin-jrh** [xmliszt/taboo-ai#266]
Browser: Firefox
OS: macOS

This issue happens to most pages in the Menu aside from Home and Choose a Topic.

Steps to replicate example:
In the About page (Top right burger > About Taboo AI), you can scroll all the way down to the bottom page and page will snap.
However, if you keep scrolling further after the snapping, the page will keep going down (empty screen all the way afterwards).

<img width="1470" alt="image" src="https://github.com/xmliszt/taboo-ai/assets/87303121/589de435-6cbd-4a3f-9612-dcdc57706fd2">

**Comment by xmliszt** [comment]
seems like it only occurs to Firefox where the native scrollbar is not hidden even after we apply `scrollbar-hide` tailwind plugin.

**Comment by austin-jrh** [comment]
Issue happens in most pages aside from Home and some other pages. Updated description to reflect this.

**Comment by xmliszt** [comment]
> Issue happens in most pages aside from Home and some other pages. Updated description to reflect this.

gg I think have to find some way to circumvent the issue using scrollbar-hide already. 👀
